fragment MaterialsParts on Materials {
  title
  linktitle
  type
  weight
  objectives {
    __typename
    objective
    explanation
  }
  body
  components {
    __typename
    ... on MaterialsComponentsModule {
      title
      filename {
        ... on Document {
          id
        }
      }
    }
    ... on MaterialsComponentsCase {
      title
      filename {
        ... on Document {
          id
        }
      }
    }
    ... on MaterialsComponentsExercise {
      title
      filename {
        ... on Document {
          id
        }
      }
    }
  }
}

fragment CasesParts on Cases {
  style
  short
  reporter
  tags
  public
  sources {
    __typename
    source_name
    source_url
    license
    attribution
  }
  body
}

fragment ModulesParts on Modules {
  title
  short
  tags
  body
}

fragment ExercisesParts on Exercises {
  title
  short
  tags
  body
}

fragment ResourcesParts on Resources {
  title
  date
  summary
  body
}
