query getMaterialsDocument($relativePath: String!) {
  getMaterialsDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...MaterialsParts
    }
  }
}

query getMaterialsList {
  getMaterialsList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...MaterialsParts
        }
      }
    }
  }
}

query getCasesDocument($relativePath: String!) {
  getCasesDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...CasesParts
    }
  }
}

query getCasesList {
  getCasesList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...CasesParts
        }
      }
    }
  }
}

query getModulesDocument($relativePath: String!) {
  getModulesDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ModulesParts
    }
  }
}

query getModulesList {
  getModulesList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ModulesParts
        }
      }
    }
  }
}

query getExercisesDocument($relativePath: String!) {
  getExercisesDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ExercisesParts
    }
  }
}

query getExercisesList {
  getExercisesList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ExercisesParts
        }
      }
    }
  }
}

query getResourcesDocument($relativePath: String!) {
  getResourcesDocument(relativePath: $relativePath) {
    sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    data {
      ...ResourcesParts
    }
  }
}

query getResourcesList {
  getResourcesList {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        data {
          ...ResourcesParts
        }
      }
    }
  }
}
